default: &default
  adapter: postgresql
  encoding: unicode

  username: postgres
  password: postgres
  host: db
  port: 5432
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: la_colmena_development

test:
  <<: *default
  database: la_colmena_test

production:
  primary: &primary_production
    <<: *default
    database_url: <%= ENV["DATABASE_URL"] %>