default: &default
  adapter: postgresql
  encoding: unicode

  username: postgres
  password: postgres
  host: db
  port: 5432
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: la_colmena_development

test:
  <<: *default
  database: la_colmena_test

production:
  primary: &primary_production
    <<: *default
    # database: la_colmena_production
    # username: la_colmena
    # password: <%= ENV["LA_COLMENA_DATABASE_PASSWORD"] %>

    database: <%= ENV["PGDATABASE"] %>
    host: <%= ENV["PGHOST"] %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    port: <%= ENV["PGPORT"] || 5432 %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

 # cache:
 #   <<: *primary_production
 #   database: la_colmena_production_cache
 #   migrations_paths: db/cache_migrate
 # queue:
 #   <<: *primary_production
 #   database: la_colmena_production_queue
 #   migrations_paths: db/queue_migrate
 # cable:
 #   <<: *primary_production
 #   database: la_colmena_production_cable
 #   migrations_paths: db/cable_migrate
