default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: db
  port: 5432
  database: la_colmena_development

test:
  <<: *default
  username: postgres
  password: postgres
  host: db
  port: 5432
  database: la_colmena_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
